// <auto-generated />
namespace BomberMan.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BomberManDB_Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BomberManDB_Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201904161104199_BomberManDB_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
