// <auto-generated />
namespace BomberMan.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BomberManDB_Change_Map_To_MapElements_And_Some_Column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BomberManDB_Change_Map_To_MapElements_And_Some_Column));
        
        string IMigrationMetadata.Id
        {
            get { return "201904241711210_BomberManDB_Change_Map_To_MapElements_And_Some_Column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
