// <auto-generated />
namespace BomberMan.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BomberManDb_SomeRefactor_in_the_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BomberManDb_SomeRefactor_in_the_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201904251626591_BomberManDb_SomeRefactor_in_the_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
